'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import toast from 'react-hot-toast'
import { Building2, UserPlus, TrendingUp, Percent, Search, SlidersHorizontal, Download, Phone, Mail, Send, Tag, X, Settings2, MoreHorizontal } from 'lucide-react'
import { LabShell, LabStatCard, LabPanel, LabBadge } from '@/components/lab'
import FormModal from '@/components/FormModal'
import { money } from '@/lib/status'

type TarifaEstandar={id:string;servicio:string;precio:number}
type Distribuidor={id:string;empresa:string;nombre_contacto:string|null;email:string;telefono:string|null;ciudad:string|null;pais:string|null;nivel:string;descuento_porcentaje:number;comision_porcentaje:number;limite_credito:number;estado:string;etiqueta:string|null;notas_internas:string|null;comercial_nombre:string|null;comercial_telefono:string|null;comercial_email:string|null;created_at:string;pedidos_30d:number;facturacion_30d:number;comision_30d:number;ordenes_recientes:{id:string;servicio:string;precio:number;created_at:string}[];tickets:{id:string;numero:string|null;asunto:string;estado:string;created_at:string}[];tickets_abiertos:number;precios:{id:string;servicio:string;precio:number}[]}
const NIVEL_TONE:Record<string,'purple'|'amber'|'zinc'|'blue'>={Platinum:'purple',Gold:'amber',Silver:'blue',Bronze:'zinc'}
const SERVICIOS_TARIFA=['Stage 1','Stage 2','DPF OFF','EGR OFF','AdBlue / SCR OFF','IMMO OFF','Pops & Bangs','Hardcut','Clone / Repair','DTC Off','Speed Limit Off']
type Tab='resumen'|'condiciones'|'precios'|'documentos'

export default function DistribuidoresPage(){
  const [rows,setRows]=useState<Distribuidor[]>([]),[ventasCanal,setVentasCanal]=useState(0),[comisionesCanal,setComisionesCanal]=useState(0),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[selectedId,setSelectedId]=useState<string|null>(null),[tab,setTab]=useState<Tab>('resumen'),[saving,setSaving]=useState(false),[form,setForm]=useState<Partial<Distribuidor>>({}),[precioDraft,setPrecioDraft]=useState<Record<string,string>>({}),[savingPrecio,setSavingPrecio]=useState<string|null>(null),[tarifaEstandar,setTarifaEstandar]=useState<TarifaEstandar[]>([]),[tarifaModalOpen,setTarifaModalOpen]=useState(false),[tarifaDraft,setTarifaDraft]=useState<Record<string,string>>({}),[savingTarifa,setSavingTarifa]=useState<string|null>(null)
  useEffect(()=>{load()},[])
  async function load(){setLoading(true);try{const res=await fetch('/api/distribuidores');const data=await res.json();if(!res.ok)throw new Error(data.error||'Error cargando distribuidores');setRows(data.distribuidores||[]);setVentasCanal(data.ventasCanal||0);setComisionesCanal(data.comisionesCanal||0);setTarifaEstandar(data.tarifaEstandar||[]);if((data.distribuidores||[]).length&&!selectedId)setSelectedId(data.distribuidores[0].id)}catch(err:any){toast.error(err.message||'No se pudieron cargar los distribuidores')}finally{setLoading(false)}}
  const estandarMap=useMemo(()=>{const map:Record<string,number>={};for(const t of tarifaEstandar)map[t.servicio]=t.precio;return map},[tarifaEstandar])
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return !q?rows:rows.filter((r)=>[r.empresa,r.nombre_contacto,r.ciudad,r.email].some((v)=>(v||'').toLowerCase().includes(q)))},[rows,query])
  const selected=rows.find((r)=>r.id===selectedId)||null
  useEffect(()=>{if(selected){setForm(selected);const draft:Record<string,string>={};for(const p of selected.precios)draft[p.servicio]=String(p.precio);setPrecioDraft(draft)}},[selectedId,rows])
  const activos=rows.filter((r)=>r.estado==='activo').length;const monthAgo=new Date();monthAgo.setDate(monthAgo.getDate()-30);const nuevos=rows.filter((r)=>new Date(r.created_at)>=monthAgo).length
  function openTarifaModal(){const draft:Record<string,string>={};for(const s of SERVICIOS_TARIFA)if(estandarMap[s]!==undefined)draft[s]=String(estandarMap[s]);setTarifaDraft(draft);setTarifaModalOpen(true)}
  async function guardarTarifaEstandar(servicio:string){const raw=tarifaDraft[servicio],precio=Number(raw);if(raw===undefined||raw===''||!Number.isFinite(precio)||precio<0){toast.error('Introduce un precio válido');return}setSavingTarifa(servicio);try{const res=await fetch('/api/distribuidores/tarifa-estandar',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({servicio,precio})});const data=await res.json();if(!res.ok)throw new Error(data.error);toast.success(`Tarifa estándar de "${servicio}" actualizada`);await load()}catch(err:any){toast.error(err.message||'No se pudo guardar la tarifa')}finally{setSavingTarifa(null)}}
  async function guardarCondiciones(){if(!selected)return;setSaving(true);try{const res=await fetch('/api/distribuidores',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,nivel:form.nivel,descuento_porcentaje:Number(form.descuento_porcentaje||0),comision_porcentaje:Number(form.comision_porcentaje||0),limite_credito:Number(form.limite_credito||0),notas_internas:form.notas_internas,comercial_nombre:form.comercial_nombre,comercial_telefono:form.comercial_telefono,comercial_email:form.comercial_email})});const data=await res.json();if(!res.ok)throw new Error(data.error);toast.success('Ficha del distribuidor actualizada');await load()}catch(err:any){toast.error(err.message||'No se pudo guardar')}finally{setSaving(false)}}
  async function guardarPrecio(servicio:string){if(!selected)return;const raw=precioDraft[servicio],precio=Number(raw);if(raw===undefined||raw===''||!Number.isFinite(precio)||precio<0){toast.error('Introduce un precio válido');return}setSavingPrecio(servicio);try{const res=await fetch('/api/distribuidores/precios',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({distribuidor_id:selected.id,servicio,precio})});const data=await res.json();if(!res.ok)throw new Error(data.error);toast.success(`Precio de "${servicio}" actualizado`);await load()}catch(err:any){toast.error(err.message||'No se pudo guardar el precio')}finally{setSavingPrecio(null)}}
  async function quitarPrecio(servicio:string){if(!selected)return;const existing=selected.precios.find((p)=>p.servicio===servicio);if(!existing)return;setSavingPrecio(servicio);try{const res=await fetch(`/api/distribuidores/precios?id=${existing.id}`,{method:'DELETE'});const data=await res.json();if(!res.ok)throw new Error(data.error);setPrecioDraft((prev)=>{const next={...prev};delete next[servicio];return next});toast.success(`"${servicio}" vuelve a la tarifa estándar`);await load()}catch(err:any){toast.error(err.message||'No se pudo quitar el precio')}finally{setSavingPrecio(null)}}

  return <LabShell title="Distribuidores" subtitle="Gestión de distribuidores y red de partners" actions={<><Link href="/ak-cloud/solicitudes" className="flex items-center gap-1.5 rounded-md bg-[#b92028] px-3.5 py-2 text-[9px] font-semibold text-white"><UserPlus size={12}/>Nuevo distribuidor</Link><button onClick={openTarifaModal} className="flex items-center gap-1 rounded-md border border-white/[0.08] px-3 py-2 text-[8px] text-zinc-500"><Settings2 size={11}/>Tarifa estándar</button><button className="flex items-center gap-1 rounded-md border border-white/[0.08] px-3 py-2 text-[8px] text-zinc-500"><Download size={11}/>Exportar</button></>}>
    <div className="space-y-3">
      <div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><LabStatCard icon={<Building2 size={18}/>} tone="green" label="Distribuidores activos" value={activos} trend={8} subtitle="vs. mes anterior"/><LabStatCard icon={<UserPlus size={18}/>} tone="blue" label="Nuevos distribuidores" value={nuevos} trend={20} subtitle="vs. mes anterior"/><LabStatCard icon={<TrendingUp size={18}/>} tone="purple" label="Ventas del canal (30d)" value={money(ventasCanal)} trend={15} subtitle="vs. mes anterior"/><LabStatCard icon={<Percent size={18}/>} tone="orange" label="Comisiones generadas" value={money(comisionesCanal)} trend={12} subtitle="vs. mes anterior"/></div>

      <div className="grid gap-3 2xl:grid-cols-[minmax(0,1fr)_410px]">
        <LabPanel padded={false}>
          <div className="grid gap-2 border-b border-white/[0.06] p-3 xl:grid-cols-[minmax(220px,1fr)_auto]"><div className="flex items-center gap-2 rounded-md border border-white/[0.08] bg-[#0c0e12] px-3 py-2"><Search size={12} className="text-zinc-600"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Buscar distribuidor..." className="w-full border-0 bg-transparent p-0 text-[9px] outline-none"/></div><button className="flex items-center gap-1 rounded-md border border-white/[0.08] px-3 py-2 text-[8px] text-zinc-500"><SlidersHorizontal size={10}/>Filtros</button></div>
          <div className="overflow-x-auto"><table className="w-full text-[8px]"><thead><tr className="text-left text-[7px] uppercase tracking-[.08em] text-zinc-600"><th className="px-3 py-3">Empresa</th><th className="px-3 py-3">Contacto</th><th className="px-3 py-3">Ciudad</th><th className="px-3 py-3">Nivel</th><th className="px-3 py-3 text-right">Descuento</th><th className="px-3 py-3 text-right">Pedidos (30d)</th><th className="px-3 py-3 text-right">Facturación (30d)</th><th className="px-3 py-3">Estado</th></tr></thead><tbody>{filtered.slice(0,12).map((d)=><tr key={d.id} onClick={()=>{setSelectedId(d.id);setTab('resumen')}} className={`cursor-pointer border-t border-white/[0.055] hover:bg-white/[0.025] ${selectedId===d.id?'bg-white/[0.018]':''}`}><td className="px-3 py-2.5 font-medium text-zinc-300">{d.empresa}</td><td className="px-3 py-2.5 text-zinc-400">{d.nombre_contacto||'—'}</td><td className="px-3 py-2.5 text-zinc-500">{[d.ciudad,d.pais].filter(Boolean).join(', ')||'—'}</td><td className="px-3 py-2.5"><LabBadge tone={NIVEL_TONE[d.nivel]||'zinc'}>{d.nivel}</LabBadge></td><td className="px-3 py-2.5 text-right text-zinc-400">{d.descuento_porcentaje}%</td><td className="px-3 py-2.5 text-right text-zinc-400">{d.pedidos_30d}</td><td className="px-3 py-2.5 text-right font-medium text-zinc-300">{money(d.facturacion_30d)}</td><td className="px-3 py-2.5"><LabBadge tone={d.estado==='activo'?'green':d.estado==='suspendido'?'amber':'red'}>{d.estado}</LabBadge></td></tr>)}{!loading&&filtered.length===0&&<tr><td colSpan={8} className="py-10 text-center text-zinc-600">Ningún distribuidor coincide con esa búsqueda.</td></tr>}</tbody></table></div>
          <div className="flex items-center justify-between border-t border-white/[0.055] px-4 py-3 text-[8px] text-zinc-600"><span>Mostrando {Math.min(filtered.length,12)} de {rows.length} distribuidores</span><div className="flex gap-1"><button className="rounded border border-white/[0.08] px-2 py-1">‹</button><button className="rounded border border-[#b92028] bg-[#8f171f] px-2.5 py-1 text-white">1</button><button className="rounded border border-white/[0.08] px-2.5 py-1">2</button><button className="rounded border border-white/[0.08] px-2 py-1">›</button></div></div>
        </LabPanel>

        <LabPanel title="Detalle del distribuidor" action={selected&&<MoreHorizontal size={13} className="text-zinc-600"/>}>
          {!selected?<div className="py-12 text-center text-[9px] text-zinc-600">Selecciona un distribuidor.</div>:<div>
            <div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-full border border-[#ef202d]/20 bg-[#ef202d]/10 text-[10px] font-semibold text-[#ef202d]">{selected.empresa.split(' ').map((w)=>w[0]).slice(0,2).join('')}</div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="truncate text-[12px] font-semibold text-zinc-200">{selected.empresa}</span><LabBadge tone={NIVEL_TONE[selected.nivel]||'zinc'}>{selected.nivel}</LabBadge></div><div className="mt-1 text-[8px] text-zinc-600">Cliente desde {new Date(selected.created_at).toLocaleDateString('es-ES')}</div></div></div>
            <div className="mt-3 grid grid-cols-2 gap-2 text-[8px]"><div><div className="text-zinc-600">Contacto principal</div><div className="mt-1 text-zinc-300">{selected.nombre_contacto||'—'}</div></div><div><div className="text-zinc-600">Estado</div><div className="mt-1"><LabBadge tone={selected.estado==='activo'?'green':'amber'}>{selected.estado}</LabBadge></div></div>{selected.telefono&&<div className="flex items-center gap-1.5 text-zinc-400"><Phone size={10}/>{selected.telefono}</div>}<div className="flex items-center gap-1.5 text-zinc-400"><Mail size={10}/>{selected.email}</div></div>
            <div className="mt-3 grid grid-cols-3 divide-x divide-white/[0.055] rounded-md border border-white/[0.055] bg-white/[0.012] py-2.5 text-center"><div><div className="text-[12px] font-semibold text-white">{selected.pedidos_30d}</div><div className="text-[7px] text-zinc-600">Pedidos 30d</div></div><div><div className="text-[12px] font-semibold text-white">{money(selected.facturacion_30d)}</div><div className="text-[7px] text-zinc-600">Facturación</div></div><div><div className="text-[12px] font-semibold text-white">{money(selected.comision_30d)}</div><div className="text-[7px] text-zinc-600">Comisión</div></div></div>
            <div className="mt-3 flex gap-3 border-b border-white/[0.055]">{(['resumen','condiciones','precios','documentos'] as Tab[]).map((t)=><button key={t} onClick={()=>setTab(t)} className={`border-b-2 px-0.5 pb-2 text-[8px] capitalize ${tab===t?'border-[#ef202d] text-zinc-200':'border-transparent text-zinc-600'}`}>{t}</button>)}</div>
            <div className="pt-3">
              {tab==='resumen'&&<div className="space-y-3"><div className="rounded-md border border-white/[0.055] bg-white/[0.012] p-2.5"><div className="mb-1 text-[8px] font-semibold text-zinc-400">Notas de cuenta</div><div className="text-[8px] leading-4 text-zinc-600">{selected.notas_internas||'Sin notas registradas.'}</div></div><div><div className="mb-1.5 text-[8px] font-semibold text-zinc-400">Órdenes recientes</div><div className="space-y-1.5">{selected.ordenes_recientes.slice(0,4).map((o)=><div key={o.id} className="flex items-center justify-between rounded-md border border-white/[0.05] px-2.5 py-2 text-[8px]"><span className="truncate text-zinc-400">{o.servicio}</span><span className="text-zinc-300">{money(o.precio)}</span></div>)}{selected.ordenes_recientes.length===0&&<div className="text-[8px] text-zinc-600">Sin ventas en los últimos 30 días.</div>}</div></div><div><div className="mb-1.5 flex justify-between text-[8px]"><span className="font-semibold text-zinc-400">Tickets de soporte</span>{selected.tickets_abiertos>0&&<LabBadge tone="amber">{selected.tickets_abiertos} abiertos</LabBadge>}</div><div className="space-y-1.5">{selected.tickets.slice(0,3).map((t)=><div key={t.id} className="flex items-center justify-between rounded-md border border-white/[0.05] px-2.5 py-2 text-[8px]"><span className="truncate text-zinc-400">{t.numero?`#${t.numero} · `:''}{t.asunto}</span><LabBadge tone={t.estado==='cerrado'?'zinc':t.estado==='en_curso'?'blue':'amber'}>{t.estado.replace('_',' ')}</LabBadge></div>)}{selected.tickets.length===0&&<div className="text-[8px] text-zinc-600">Sin tickets.</div>}</div></div><div className="rounded-md border border-white/[0.055] bg-white/[0.012] p-2.5"><div className="mb-2 text-[8px] font-semibold text-zinc-400">Comercial asignado</div>{selected.comercial_nombre?<div className="flex items-center justify-between"><div><div className="text-[9px] font-medium text-zinc-300">{selected.comercial_nombre}</div><div className="text-[7px] text-zinc-600">{selected.comercial_telefono}</div></div>{selected.comercial_email&&<a href={`mailto:${selected.comercial_email}`} className="flex items-center gap-1 rounded border border-white/[0.06] px-2 py-1.5 text-[7px] text-zinc-500"><Send size={9}/>Enviar mensaje</a>}</div>:<div className="text-[8px] text-zinc-600">Sin comercial asignado.</div>}</div></div>}
              {tab==='condiciones'&&<div className="grid grid-cols-2 gap-2"><Field label="Nivel"><select value={form.nivel||'Bronze'} onChange={(e)=>setForm({...form,nivel:e.target.value})}>{['Platinum','Gold','Silver','Bronze'].map((n)=><option key={n}>{n}</option>)}</select></Field><Field label="Descuento %"><input type="number" value={form.descuento_porcentaje??0} onChange={(e)=>setForm({...form,descuento_porcentaje:Number(e.target.value)})}/></Field><Field label="Comisión %"><input type="number" value={form.comision_porcentaje??0} onChange={(e)=>setForm({...form,comision_porcentaje:Number(e.target.value)})}/></Field><Field label="Límite crédito"><input type="number" value={form.limite_credito??0} onChange={(e)=>setForm({...form,limite_credito:Number(e.target.value)})}/></Field><Field label="Comercial" span><input value={form.comercial_nombre||''} onChange={(e)=>setForm({...form,comercial_nombre:e.target.value})}/></Field><Field label="Teléfono"><input value={form.comercial_telefono||''} onChange={(e)=>setForm({...form,comercial_telefono:e.target.value})}/></Field><Field label="Email"><input value={form.comercial_email||''} onChange={(e)=>setForm({...form,comercial_email:e.target.value})}/></Field><Field label="Notas" span><textarea rows={3} value={form.notas_internas||''} onChange={(e)=>setForm({...form,notas_internas:e.target.value})}/></Field><button onClick={guardarCondiciones} disabled={saving} className="col-span-2 rounded-md bg-[#b92028] py-2 text-[8px] font-semibold text-white disabled:opacity-50">{saving?'Guardando...':'Guardar condiciones'}</button></div>}
              {tab==='precios'&&<div className="space-y-1.5">{SERVICIOS_TARIFA.map((servicio)=>{const tiene=selected.precios.some((p)=>p.servicio===servicio);const estandar=estandarMap[servicio];return <div key={servicio} className="flex items-center gap-2 rounded-md border border-white/[0.05] px-2 py-1.5"><Tag size={9} className="text-zinc-700"/><div className="min-w-0 flex-1"><div className="truncate text-[8px] text-zinc-400">{servicio}</div><div className="text-[7px] text-zinc-700">Estándar: {estandar!==undefined?`${estandar.toFixed(2)} €`:'sin fijar'}</div></div><input type="number" step="0.01" placeholder={estandar!==undefined?estandar.toFixed(2):'0.00'} value={precioDraft[servicio]??''} onChange={(e)=>setPrecioDraft((p)=>({...p,[servicio]:e.target.value}))} className="w-16 text-right text-[8px]"/><button onClick={()=>guardarPrecio(servicio)} disabled={savingPrecio===servicio} className="rounded bg-[#8f171f] px-2 py-1.5 text-[7px] text-white">Guardar</button>{tiene&&<button onClick={()=>quitarPrecio(servicio)} className="text-zinc-600"><X size={10}/></button>}</div>})}</div>}
              {tab==='documentos'&&<div className="py-10 text-center text-[8px] text-zinc-600">Sin documentos todavía.</div>}
            </div>
          </div>}
        </LabPanel>
      </div>
    </div>

    <FormModal open={tarifaModalOpen} onClose={()=>setTarifaModalOpen(false)} title="Tarifa estándar"><p className="mb-3 text-[9px] text-zinc-500">Precio de catálogo para distribuidores sin tarifa propia.</p><div className="space-y-1.5">{SERVICIOS_TARIFA.map((servicio)=><div key={servicio} className="flex items-center gap-2 rounded-md border border-white/[0.05] px-2.5 py-2"><Tag size={10} className="text-zinc-700"/><span className="min-w-0 flex-1 text-[8px] text-zinc-400">{servicio}</span><input type="number" step="0.01" value={tarifaDraft[servicio]??''} onChange={(e)=>setTarifaDraft((p)=>({...p,[servicio]:e.target.value}))} className="w-20 text-right text-[8px]"/><button onClick={()=>guardarTarifaEstandar(servicio)} disabled={savingTarifa===servicio} className="rounded bg-[#b92028] px-2.5 py-1.5 text-[7px] text-white">Guardar</button></div>)}</div></FormModal>
  </LabShell>
}
function Field({label,children,span=false}:{label:string;children:React.ReactNode;span?:boolean}){return <label className={span?'col-span-2':''}><span className="mb-1 block text-[7px] text-zinc-600">{label}</span>{children}</label>}
