'use client'

import { useEffect, useMemo, useState } from 'react'
import toast from 'react-hot-toast'
import { Package, AlertTriangle, Boxes, ArrowDownToLine, ArrowUpFromLine, Search, SlidersHorizontal, Download, Settings2, Cpu, Pencil, Trash2, Plus } from 'lucide-react'
import { LabShell, LabStatCard, LabPanel, LabBadge } from '@/components/lab'
import FormModal from '@/components/FormModal'
import ConfirmModal from '@/components/ConfirmModal'
import { supabase } from '@/lib/supabase'
import { money } from '@/lib/status'

const tiposStock=['llave','ecu','bsi','bcm','cas','fem','bdc','ezs','elv','cuadro','accesorio','otro']
const emptyForm={tipo:'otro',referencia:'',descripcion:'',marca:'',modelo:'',cantidad:0,cantidad_minima:0,precio_compra:0,precio_venta:0,ubicacion:'',notas:''}
function estadoStock(item:any){const c=Number(item.cantidad||0),m=Number(item.cantidad_minima||0);if(c<=0||(m>0&&c<=m*.5))return{tone:'red' as const,label:'Crítico'};if(c<=m)return{tone:'amber' as const,label:'Bajo stock'};return{tone:'green' as const,label:'OK'}}
function categoryTone(tipo:string){if(['ecu','bsi','bcm','cas','fem','bdc','ezs','elv'].includes(tipo))return'blue';if(tipo==='llave')return'purple';if(tipo==='accesorio')return'orange';return'zinc'}

export default function StockPage(){
  const [items,setItems]=useState<any[]>([]),[movimientos,setMovimientos]=useState<any[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<any|null>(null),[form,setForm]=useState<any>(emptyForm),[query,setQuery]=useState(''),[tipoFiltro,setTipoFiltro]=useState('todos'),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[pendingDelete,setPendingDelete]=useState<any|null>(null),[deleting,setDeleting]=useState(false),[selectedId,setSelectedId]=useState<string|null>(null)
  useEffect(()=>{load()},[])
  async function load(){try{setLoading(true);const [stockRes,movRes]=await Promise.all([supabase.from('stock').select('*').order('created_at',{ascending:false}),supabase.from('movimientos_stock').select('*, stock:stock_id(referencia,descripcion)').order('created_at',{ascending:false}).limit(8)]);if(stockRes.error)throw stockRes.error;setItems(stockRes.data||[]);setMovimientos(movRes.data||[]);if((stockRes.data||[]).length&&!selectedId)setSelectedId(stockRes.data![0].id)}catch(error:any){toast.error(error.message||'No se pudo cargar el stock')}finally{setLoading(false)}}
  const stockBajo=items.filter((i)=>Number(i.cantidad||0)<=Number(i.cantidad_minima||0));const valorInventario=items.reduce((s,i)=>s+Number(i.cantidad||0)*Number(i.precio_venta||i.precio_compra||0),0);const entradasMes=movimientos.filter((m)=>m.tipo_movimiento==='entrada').reduce((a,m)=>a+Number(m.cantidad||0),0);const salidasMes=movimientos.filter((m)=>m.tipo_movimiento==='salida').reduce((a,m)=>a+Math.abs(Number(m.cantidad||0)),0)
  const filtered=useMemo(()=>{let out=tipoFiltro==='todos'?items:items.filter((i)=>(i.tipo||'otro')===tipoFiltro);const q=query.toLowerCase().trim();return !q?out:out.filter((i)=>`${i.tipo||''} ${i.referencia||''} ${i.descripcion||''} ${i.marca||''} ${i.modelo||''} ${i.ubicacion||''}`.toLowerCase().includes(q))},[items,query,tipoFiltro])
  const selected=items.find((i)=>i.id===selectedId)||null;const margen=selected&&Number(selected.precio_venta)>0?((Number(selected.precio_venta)-Number(selected.precio_compra||0))/Number(selected.precio_venta))*100:null;const ultimaEntrada=movimientos.find((m)=>m.stock_id===selected?.id&&m.tipo_movimiento==='entrada');const badgeSel=selected?estadoStock(selected):null
  function newItem(){setEditing(null);setForm(emptyForm);setOpen(true)}
  function editItem(item:any){setEditing(item);setForm({tipo:item.tipo||'otro',referencia:item.referencia||'',descripcion:item.descripcion||'',marca:item.marca||'',modelo:item.modelo||'',cantidad:item.cantidad??0,cantidad_minima:item.cantidad_minima??0,precio_compra:item.precio_compra??0,precio_venta:item.precio_venta??0,ubicacion:item.ubicacion||'',notas:item.notas||''});setOpen(true)}
  async function save(e:any){e.preventDefault();if(!form.descripcion?.trim()){toast.error('La descripción es obligatoria');return}try{setSaving(true);const payload={tipo:form.tipo||'otro',referencia:form.referencia||null,descripcion:form.descripcion,marca:form.marca||null,modelo:form.modelo||null,cantidad:Number(form.cantidad||0),cantidad_minima:Number(form.cantidad_minima||0),precio_compra:Number(form.precio_compra||0),precio_venta:Number(form.precio_venta||0),ubicacion:form.ubicacion||null,notas:form.notas||null};if(editing){const{error}=await supabase.from('stock').update(payload).eq('id',editing.id);if(error)throw error;await supabase.from('movimientos_stock').insert({stock_id:editing.id,tipo_movimiento:'ajuste',cantidad:payload.cantidad,motivo:'Edición manual desde control de stock'});toast.success('Referencia actualizada')}else{const{error}=await supabase.from('stock').insert(payload);if(error)throw error;toast.success('Referencia creada')}setOpen(false);setEditing(null);setForm(emptyForm);await load()}catch(error:any){toast.error(error.message||'No se pudo guardar')}finally{setSaving(false)}}
  async function confirmDelete(){if(!pendingDelete)return;setDeleting(true);const{error}=await supabase.from('stock').delete().eq('id',pendingDelete.id);setDeleting(false);if(error){toast.error(error.message);return}toast.success('Referencia eliminada');setPendingDelete(null);if(selectedId===pendingDelete.id)setSelectedId(null);load()}

  return <LabShell title="Stock" subtitle="Inventario / Gestión de stock" actions={<button onClick={newItem} className="flex items-center gap-1.5 rounded-md bg-[#b92028] px-3.5 py-2 text-[10px] font-semibold text-white"><Plus size={12}/>Nueva referencia</button>}>
    <div className="space-y-3">
      <div className="grid grid-cols-2 gap-3 xl:grid-cols-5"><LabStatCard icon={<Boxes size={18}/>} tone="red" label="Artículos totales" value={items.length.toLocaleString('es-ES')} trend={5.3} subtitle="vs. mes anterior"/><LabStatCard icon={<AlertTriangle size={18}/>} tone="orange" label="Bajo stock" value={stockBajo.length} trend={-8.2} subtitle="Requieren reposición"/><LabStatCard icon={<Package size={18}/>} tone="blue" label="Valor de inventario" value={money(valorInventario)} trend={6.7} subtitle="Valor total actual"/><LabStatCard icon={<ArrowDownToLine size={18}/>} tone="green" label="Entradas (este mes)" value={entradasMes} trend={18.4} subtitle="Unidades recibidas"/><LabStatCard icon={<ArrowUpFromLine size={18}/>} tone="purple" label="Salidas (este mes)" value={salidasMes} trend={14.1} subtitle="Unidades despachadas"/></div>

      <div className="grid gap-3 2xl:grid-cols-[minmax(0,1fr)_340px]">
        <LabPanel padded={false}>
          <div className="grid gap-2 border-b border-white/[0.06] p-3 xl:grid-cols-[170px_minmax(220px,1fr)_auto_auto_auto]"><select value={tipoFiltro} onChange={(e)=>setTipoFiltro(e.target.value)} className="rounded-md border border-white/[0.08] bg-[#0c0e12] px-3 py-2 text-[9px]"><option value="todos">Todas las categorías</option>{tiposStock.map((t)=><option key={t} value={t}>{t.toUpperCase()}</option>)}</select><div className="flex items-center gap-2 rounded-md border border-white/[0.08] bg-[#0c0e12] px-3 py-2"><Search size={12} className="text-zinc-600"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Buscar por SKU, referencia o descripción..." className="w-full border-0 bg-transparent p-0 text-[9px] outline-none"/></div><button className="flex items-center gap-1 rounded-md border border-white/[0.08] px-2.5 py-2 text-[8px] text-zinc-500"><SlidersHorizontal size={10}/>Filtros</button><button className="flex items-center gap-1 rounded-md border border-white/[0.08] px-2.5 py-2 text-[8px] text-zinc-500"><Download size={10}/>Exportar</button><button className="flex items-center gap-1 rounded-md border border-white/[0.08] px-2.5 py-2 text-[8px] text-zinc-500"><Settings2 size={10}/>Ajustes de vista</button></div>
          <div className="overflow-x-auto"><table className="w-full text-[8px]"><thead><tr className="text-left text-[7px] uppercase tracking-[.08em] text-zinc-600"><th className="px-3 py-3">Categoría</th><th className="px-3 py-3">SKU</th><th className="px-3 py-3">Descripción</th><th className="px-3 py-3">Ubicación</th><th className="px-3 py-3 text-right">Stock</th><th className="px-3 py-3 text-right">Mínimo</th><th className="px-3 py-3 text-right">Coste</th><th className="px-3 py-3 text-right">PVP</th><th className="px-3 py-3">Estado</th><th/></tr></thead><tbody>{filtered.slice(0,12).map((item)=>{const st=estadoStock(item);return <tr key={item.id} onClick={()=>setSelectedId(item.id)} className={`cursor-pointer border-t border-white/[0.055] hover:bg-white/[0.025] ${selectedId===item.id?'bg-white/[0.018]':''}`}><td className="px-3 py-2.5"><LabBadge tone={categoryTone(item.tipo||'otro') as any}>{(item.tipo||'otro').toUpperCase()}</LabBadge></td><td className="px-3 py-2.5 font-medium text-zinc-300">{item.referencia||'—'}</td><td className="px-3 py-2.5"><div className="text-zinc-300">{item.descripcion}</div><div className="mt-0.5 text-[7px] text-zinc-600">{[item.marca,item.modelo].filter(Boolean).join(' ')}</div></td><td className="px-3 py-2.5 text-zinc-500">{item.ubicacion||'—'}</td><td className={`px-3 py-2.5 text-right font-semibold ${Number(item.cantidad)<=Number(item.cantidad_minima)?'text-[#ef202d]':'text-zinc-300'}`}>{item.cantidad??0}</td><td className="px-3 py-2.5 text-right text-zinc-600">{item.cantidad_minima??0}</td><td className="px-3 py-2.5 text-right text-zinc-500">{money(item.precio_compra)}</td><td className="px-3 py-2.5 text-right text-zinc-300">{money(item.precio_venta)}</td><td className="px-3 py-2.5"><LabBadge tone={st.tone} dot>{st.label}</LabBadge></td><td className="px-2"><div className="flex gap-1"><button onClick={(e)=>{e.stopPropagation();editItem(item)}} className="text-zinc-600 hover:text-white"><Pencil size={11}/></button><button onClick={(e)=>{e.stopPropagation();setPendingDelete(item)}} className="text-zinc-600 hover:text-red-400"><Trash2 size={11}/></button></div></td></tr>})}{!loading&&filtered.length===0&&<tr><td colSpan={10} className="py-10 text-center text-zinc-600">Ninguna referencia coincide con estos filtros.</td></tr>}</tbody></table></div>
          <div className="flex items-center justify-between border-t border-white/[0.055] px-4 py-3 text-[8px] text-zinc-600"><span>Mostrando {Math.min(filtered.length,12)} de {filtered.length} referencias</span><div className="flex gap-1"><button className="rounded border border-white/[0.08] px-2 py-1">‹</button><button className="rounded border border-[#b92028] bg-[#8f171f] px-2.5 py-1 text-white">1</button><button className="rounded border border-white/[0.08] px-2.5 py-1">2</button><button className="rounded border border-white/[0.08] px-2 py-1">›</button></div></div>
        </LabPanel>

        <LabPanel title="Detalle del artículo" action={selected&&<button onClick={()=>editItem(selected)} className="rounded border border-white/[0.07] px-2 py-1 text-[7px] text-zinc-500">Editar</button>}>
          {!selected?<div className="py-12 text-center text-[9px] text-zinc-600">Selecciona un artículo.</div>:<div className="space-y-3"><div className="grid h-24 place-items-center rounded-lg border border-white/[0.055] bg-[radial-gradient(circle_at_center,rgba(255,255,255,.06),transparent_65%)]"><Cpu size={45} strokeWidth={1} className="text-zinc-600"/></div><div className="flex gap-2"><LabBadge tone={categoryTone(selected.tipo||'otro') as any}>{(selected.tipo||'otro').toUpperCase()}</LabBadge>{badgeSel&&<LabBadge tone={badgeSel.tone}>{badgeSel.label==='OK'?'En stock':badgeSel.label}</LabBadge>}</div><div><div className="text-[12px] font-semibold text-zinc-200">{selected.descripcion}</div><div className="mt-1 text-[8px] text-zinc-600">{[selected.marca,selected.modelo].filter(Boolean).join(' ')}</div></div><dl className="text-[8px]">{[['SKU',selected.referencia||'—'],['Ubicación',selected.ubicacion||'—'],['Stock actual',`${selected.cantidad??0} unidades`],['Stock mínimo',`${selected.cantidad_minima??0} unidades`],['Coste',money(selected.precio_compra)],['PVP',money(selected.precio_venta)],['Margen',margen!==null?`${margen.toFixed(1)}%`:'—'],['Última entrada',ultimaEntrada?new Date(ultimaEntrada.created_at).toLocaleDateString('es-ES'):'—']].map(([k,v])=><div key={k} className="flex justify-between border-b border-white/[0.045] py-1.5"><dt className="text-zinc-600">{k}</dt><dd className={k==='Margen'?'text-[#55c765]':'text-zinc-300'}>{v}</dd></div>)}</dl>{selected.notas&&<div className="rounded-md border border-white/[0.055] bg-white/[0.015] p-2.5 text-[8px] leading-4 text-zinc-500">{selected.notas}</div>}</div>}
        </LabPanel>
      </div>

      <div className="grid gap-3 xl:grid-cols-2"><LabPanel title="Alertas de reposición" action={<LabBadge tone="red">{stockBajo.length}</LabBadge>}><div className="space-y-1.5">{stockBajo.slice(0,5).map((item)=>{const critico=Number(item.cantidad)<=Number(item.cantidad_minima)*.5;return <div key={item.id} className="flex items-center justify-between gap-3 rounded-md border border-white/[0.055] bg-white/[0.012] px-3 py-2"><div className="min-w-0"><div className="truncate text-[9px] font-medium text-zinc-300">{item.descripcion}</div><div className="mt-0.5 text-[7px] text-zinc-600">SKU: {item.referencia||'—'} · {item.cantidad??0}/{item.cantidad_minima??0} uds</div></div><button className={`shrink-0 rounded-md px-2.5 py-1.5 text-[7px] font-semibold ${critico?'bg-[#b92028] text-white':'border border-[#f59e0b]/25 bg-[#f59e0b]/10 text-[#f59e0b]'}`}>{critico?'Realizar pedido':'Programar pedido'}</button></div>})}{stockBajo.length===0&&<div className="py-6 text-center text-[8px] text-zinc-600">Sin alertas de reposición.</div>}</div></LabPanel>
        <LabPanel title="Movimientos recientes"><div className="space-y-1.5">{movimientos.map((m)=><div key={m.id} className="flex items-center justify-between gap-3 rounded-md border border-white/[0.055] bg-white/[0.012] px-3 py-2 text-[8px]"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><LabBadge tone={m.tipo_movimiento==='entrada'?'green':m.tipo_movimiento==='salida'?'red':'blue'}>{m.tipo_movimiento}</LabBadge><span className="truncate text-zinc-300">{m.stock?.descripcion||m.stock?.referencia||'Referencia'}</span></div><div className="mt-1 text-[7px] text-zinc-600">{new Date(m.created_at).toLocaleString('es-ES')}{m.motivo?` · ${m.motivo}`:''}</div></div><span className={m.tipo_movimiento==='salida'?'text-[#ef202d]':'text-[#55c765]'}>{m.tipo_movimiento==='salida'?'-':'+'}{Math.abs(Number(m.cantidad||0))}</span></div>)}{movimientos.length===0&&<div className="py-6 text-center text-[8px] text-zinc-600">Sin movimientos registrados.</div>}</div></LabPanel></div>
    </div>

    <FormModal open={open} onClose={()=>setOpen(false)} title={editing?'Editar referencia':'Nueva referencia'}><form onSubmit={save} className="grid gap-3 md:grid-cols-2"><select value={form.tipo} onChange={(e)=>setForm({...form,tipo:e.target.value})}>{tiposStock.map((x)=><option key={x} value={x}>{x}</option>)}</select><input placeholder="Referencia" value={form.referencia} onChange={(e)=>setForm({...form,referencia:e.target.value})}/><input required className="md:col-span-2" placeholder="Descripción" value={form.descripcion} onChange={(e)=>setForm({...form,descripcion:e.target.value})}/><input placeholder="Marca" value={form.marca} onChange={(e)=>setForm({...form,marca:e.target.value})}/><input placeholder="Modelo" value={form.modelo} onChange={(e)=>setForm({...form,modelo:e.target.value})}/><input type="number" placeholder="Cantidad" value={form.cantidad} onChange={(e)=>setForm({...form,cantidad:Number(e.target.value)})}/><input type="number" placeholder="Cantidad mínima" value={form.cantidad_minima} onChange={(e)=>setForm({...form,cantidad_minima:Number(e.target.value)})}/><input type="number" step="0.01" placeholder="Precio compra" value={form.precio_compra} onChange={(e)=>setForm({...form,precio_compra:Number(e.target.value)})}/><input type="number" step="0.01" placeholder="Precio venta" value={form.precio_venta} onChange={(e)=>setForm({...form,precio_venta:Number(e.target.value)})}/><input className="md:col-span-2" placeholder="Ubicación" value={form.ubicacion} onChange={(e)=>setForm({...form,ubicacion:e.target.value})}/><textarea className="md:col-span-2" placeholder="Notas" value={form.notas} onChange={(e)=>setForm({...form,notas:e.target.value})}/><button disabled={saving} className="rounded-md bg-[#b92028] py-2.5 text-[10px] font-semibold text-white disabled:opacity-50 md:col-span-2">{saving?'Guardando...':editing?'Guardar cambios':'Crear referencia'}</button></form></FormModal>
    <ConfirmModal open={Boolean(pendingDelete)} title={`Eliminar ${pendingDelete?.referencia||pendingDelete?.descripcion||'esta referencia'}`} description="Se eliminará la referencia de stock definitivamente." confirmLabel="Sí, eliminar" danger loading={deleting} onConfirm={confirmDelete} onCancel={()=>setPendingDelete(null)}/>
  </LabShell>
}
