'use client'

import { useEffect, useMemo, useState } from 'react'
import toast from 'react-hot-toast'
import { Users, Package, Lock, Clock, SlidersHorizontal, FileText, ClipboardList, Truck, Receipt, MoreVertical, Eye, Printer, CheckCircle2, Trash2 } from 'lucide-react'
import { LabShell, LabStatCard, LabPanel, LabBadge, LabLineChart, LabBarChart, LabDonut } from '@/components/lab'
import FormModal from '@/components/FormModal'
import ConfirmModal from '@/components/ConfirmModal'
import { supabase } from '@/lib/supabase'
import { money } from '@/lib/status'

type Documento={id:string;cliente_id?:string|null;tipo_documento?:string|null;numero_documento?:string|null;fecha?:string|null;subtotal?:number|null;iva_importe?:number|null;total?:number|null;estado?:string|null;created_at?:string;clientes?:{nombre?:string|null}|null;concepto?:string}
const emptyForm={tipo_documento:'factura',cliente_id:'',estado:'pendiente',iva_porcentaje:21,notas:'',concepto:'Servicio Autokeys Lab',precio:0}
function isVencida(doc:Documento){if(doc.estado!=='pendiente'||!doc.fecha)return false;return (Date.now()-new Date(doc.fecha).getTime())/86400000>15}
function estadoInfo(doc:Documento){if(doc.estado==='pagada')return{tone:'green' as const,label:'Pagada'};if(doc.estado==='cancelada')return{tone:'zinc' as const,label:'Cancelada'};if(isVencida(doc))return{tone:'red' as const,label:'Vencida'};return{tone:'amber' as const,label:'Pendiente'}}
function daysInMonth(){const now=new Date();return new Date(now.getFullYear(),now.getMonth()+1,0).getDate()}

export default function FacturasPage(){
  const [items,setItems]=useState<Documento[]>([]);const [clientes,setClientes]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [tipoFiltro,setTipoFiltro]=useState('todas');const [open,setOpen]=useState(false);const [form,setForm]=useState<any>(emptyForm);const [menuOpen,setMenuOpen]=useState<string|null>(null);const [pendingDelete,setPendingDelete]=useState<Documento|null>(null);const [deleting,setDeleting]=useState(false)
  useEffect(()=>{load()},[])
  async function load(){setLoading(true);try{const [{data:docs,error:docsError},{data:cli,error:cliError}]=await Promise.all([supabase.from('facturas').select('*,clientes(nombre)').order('created_at',{ascending:false}),supabase.from('clientes').select('id,nombre').order('nombre')]);if(docsError)throw docsError;if(cliError)throw cliError;const rows=(docs||[]) as Documento[];const ids=rows.slice(0,10).map((r)=>r.id);if(ids.length){const {data:lineas}=await supabase.from('lineas_factura').select('factura_id,concepto').in('factura_id',ids);const map=new Map<string,string>();for(const l of lineas||[])if(!map.has(l.factura_id))map.set(l.factura_id,l.concepto);rows.forEach((r)=>{r.concepto=map.get(r.id)})}setItems(rows);setClientes(cli||[])}catch(error:any){toast.error(error.message||'No se pudieron cargar los documentos')}finally{setLoading(false)}}
  const filtered=useMemo(()=>tipoFiltro==='todas'?items:items.filter((i)=>i.tipo_documento===tipoFiltro),[items,tipoFiltro])
  const today=new Date().toISOString().slice(0,10);const monthStart=today.slice(0,7)+'-01';const facturadoHoy=items.filter((i)=>(i.fecha||i.created_at||'').startsWith(today)).reduce((a,i)=>a+Number(i.total||0),0);const facturasEsteMes=items.filter((i)=>(i.fecha||i.created_at||'')>=monthStart);const facturadoMes=facturasEsteMes.reduce((a,i)=>a+Number(i.total||0),0);const pendientes=items.filter((i)=>i.estado==='pendiente'||isVencida(i));const pendienteTotal=pendientes.reduce((a,i)=>a+Number(i.total||0),0);const ticketMedio=facturasEsteMes.length?facturadoMes/facturasEsteMes.length:0
  const dias=daysInMonth();const dayLabels=Array.from({length:dias},(_,i)=>String(i+1).padStart(2,'0'));const ingresosPorDia=Array.from({length:dias},()=>0);const cobradosPorDia=Array.from({length:dias},()=>0);const pendientesPorDia=Array.from({length:dias},()=>0);for(const i of facturasEsteMes){const d=Number((i.fecha||i.created_at||'').slice(8,10))-1;if(d<0||d>=dias)continue;ingresosPorDia[d]+=Number(i.total||0);if(i.estado==='pagada')cobradosPorDia[d]+=Number(i.total||0);else pendientesPorDia[d]+=Number(i.total||0)}const ingresosAcumulado=ingresosPorDia.reduce<number[]>((acc,v,idx)=>{acc.push((acc[idx-1]||0)+v);return acc},[])
  const cobradas=items.filter((i)=>i.estado==='pagada').reduce((a,i)=>a+Number(i.total||0),0);const vencidas=items.filter((i)=>isVencida(i)).reduce((a,i)=>a+Number(i.total||0),0);const pendientesSinVencer=pendienteTotal-vencidas;const totalCobros=cobradas+pendienteTotal||1
  async function save(e:any){e.preventDefault();try{const {data,error}=await supabase.from('facturas').insert({tipo_documento:form.tipo_documento,cliente_id:form.cliente_id||null,estado:form.estado||'pendiente',iva_porcentaje:Number(form.iva_porcentaje||21),notas:form.notas||null}).select('*').single();if(error)throw error;const precio=Number(form.precio||0);if(form.concepto||precio>0)await supabase.from('lineas_factura').insert({factura_id:data.id,concepto:form.concepto||'Servicio Autokeys Lab',cantidad:1,precio_unitario:precio});toast.success('Documento creado');setOpen(false);setForm(emptyForm);await load()}catch(error:any){toast.error(error.message||'Error guardando documento')}}
  function crearDocumento(tipo:string){setForm({...emptyForm,tipo_documento:tipo});setOpen(true)}
  function abrirDocumento(id:string,imprimir=false){window.open(imprimir?`/api/documentos/${id}?print=1`:`/api/documentos/${id}`,'_blank','noopener,noreferrer');setMenuOpen(null)}
  async function marcarPagada(doc:Documento){const {error}=await supabase.from('facturas').update({estado:'pagada'}).eq('id',doc.id);setMenuOpen(null);if(error){toast.error(error.message);return}toast.success('Documento marcado como pagada');load()}
  async function confirmDelete(){if(!pendingDelete)return;setDeleting(true);const {error}=await supabase.from('facturas').delete().eq('id',pendingDelete.id);setDeleting(false);if(error){toast.error(error.message);return}toast.success('Documento eliminado');setPendingDelete(null);load()}
  const quickDocs=[{tipo:'factura',label:'Factura',desc:'Generar nueva factura',icon:FileText,tone:'red'},{tipo:'presupuesto',label:'Presupuesto',desc:'Crear presupuesto',icon:ClipboardList,tone:'orange'},{tipo:'albaran',label:'Albarán',desc:'Generar albarán de entrega',icon:Truck,tone:'green'},{tipo:'ticket',label:'Ticket',desc:'Crear ticket de venta',icon:Receipt,tone:'purple'}]

  return <LabShell>
    <div className="space-y-3">
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><LabStatCard icon={<Users size={18}/>} tone="zinc" label="Facturado hoy" value={money(facturadoHoy)} trend={18} subtitle="vs ayer"/><LabStatCard icon={<Package size={18}/>} tone="zinc" label="Facturado este mes" value={money(facturadoMes)} trend={22} subtitle="vs mes anterior"/><LabStatCard icon={<Lock size={18}/>} tone="orange" label="Pendiente de cobro" value={money(pendienteTotal)} subtitle={`${pendientes.length} facturas`}/><LabStatCard icon={<Clock size={18}/>} tone="zinc" label="Ticket medio" value={money(ticketMedio)} trend={8} subtitle="vs mes anterior"/></div>
      <div className="grid gap-3 2xl:grid-cols-[minmax(0,1fr)_315px]">
        <LabPanel padded={false}>
          <div className="flex items-center justify-between border-b border-white/[0.06] px-4 py-3"><h2 className="text-[13px] font-semibold text-white">Facturas recientes</h2><div className="flex gap-2"><select value={tipoFiltro} onChange={(e)=>setTipoFiltro(e.target.value)} className="rounded-md border border-white/[0.08] bg-[#0d0f12] px-2.5 py-1.5 text-[8px]"><option value="todas">Ver: Todas</option><option value="factura">Facturas</option><option value="presupuesto">Presupuestos</option><option value="albaran">Albaranes</option><option value="ticket">Tickets</option></select><button className="flex items-center gap-1 rounded-md border border-white/[0.08] px-2.5 py-1.5 text-[8px] text-zinc-500"><SlidersHorizontal size={10}/>Filtros</button></div></div>
          <div className="overflow-x-auto"><table className="w-full text-[8px]"><thead><tr className="text-left text-[7px] uppercase tracking-[.08em] text-zinc-600"><th className="px-3 py-3">Número</th><th className="px-3 py-3">Cliente</th><th className="px-3 py-3">Concepto</th><th className="px-3 py-3 text-right">Base imponible</th><th className="px-3 py-3 text-right">IVA</th><th className="px-3 py-3 text-right">Total</th><th className="px-3 py-3">Estado de pago</th><th className="px-3 py-3">Vencimiento</th><th/></tr></thead><tbody>{filtered.slice(0,8).map((doc)=>{const info=estadoInfo(doc);return <tr key={doc.id} className="border-t border-white/[0.055] hover:bg-white/[0.02]"><td className="px-3 py-2.5 font-medium text-zinc-300">{doc.numero_documento||'Sin número'}</td><td className="px-3 py-2.5 text-zinc-300">{doc.clientes?.nombre||'—'}</td><td className="px-3 py-2.5 text-zinc-400">{doc.concepto||doc.tipo_documento}</td><td className="px-3 py-2.5 text-right text-zinc-400">{money(doc.subtotal)}</td><td className="px-3 py-2.5 text-right text-zinc-400">{money(doc.iva_importe)}</td><td className="px-3 py-2.5 text-right font-medium text-zinc-200">{money(doc.total)}</td><td className="px-3 py-2.5"><LabBadge tone={info.tone}>{info.label}</LabBadge></td><td className="px-3 py-2.5 text-zinc-500">{doc.fecha?new Date(doc.fecha).toLocaleDateString('es-ES'):'—'}</td><td className="relative px-2"><button onClick={()=>setMenuOpen(menuOpen===doc.id?null:doc.id)} className="text-zinc-600"><MoreVertical size={12}/></button>{menuOpen===doc.id&&<div className="absolute right-2 top-7 z-20 w-36 rounded-lg border border-white/[0.09] bg-[#0d0f13] p-1 shadow-2xl"><button onClick={()=>abrirDocumento(doc.id)} className="flex w-full items-center gap-2 rounded px-2 py-1.5 text-left text-[8px] text-zinc-300 hover:bg-white/[0.04]"><Eye size={10}/>Ver PDF</button><button onClick={()=>abrirDocumento(doc.id,true)} className="flex w-full items-center gap-2 rounded px-2 py-1.5 text-left text-[8px] text-zinc-300 hover:bg-white/[0.04]"><Printer size={10}/>Imprimir</button>{doc.estado!=='pagada'&&<button onClick={()=>marcarPagada(doc)} className="flex w-full items-center gap-2 rounded px-2 py-1.5 text-left text-[8px] text-[#55c765]"><CheckCircle2 size={10}/>Marcar pagada</button>}<button onClick={()=>{setPendingDelete(doc);setMenuOpen(null)}} className="flex w-full items-center gap-2 rounded px-2 py-1.5 text-left text-[8px] text-red-400"><Trash2 size={10}/>Eliminar</button></div>}</td></tr>})}{!loading&&filtered.length===0&&<tr><td colSpan={9} className="py-10 text-center text-zinc-600">Todavía no hay documentos.</td></tr>}</tbody></table></div>
          <button className="w-full border-t border-white/[0.055] py-2.5 text-[8px] text-zinc-500">Ver todas las facturas</button>
        </LabPanel>
        <LabPanel title="Crear nuevo documento"><div className="space-y-2">{quickDocs.map((d)=>{const Icon=d.icon;const colors:any={red:'bg-[#ef202d]/12 text-[#ef202d]',orange:'bg-[#f59e0b]/12 text-[#f59e0b]',green:'bg-[#55c765]/12 text-[#55c765]',purple:'bg-[#8b5cf6]/12 text-[#8b5cf6]'};return <button key={d.tipo} onClick={()=>crearDocumento(d.tipo)} className="flex w-full items-center gap-3 rounded-lg border border-white/[0.06] bg-white/[0.012] p-3 text-left hover:bg-white/[0.03]"><div className={`grid h-9 w-9 place-items-center rounded-lg ${colors[d.tone]}`}><Icon size={15}/></div><div><div className="text-[10px] font-medium text-zinc-200">{d.label}</div><div className="mt-0.5 text-[8px] text-zinc-600">{d.desc}</div></div></button>})}</div></LabPanel>
      </div>
      <div className="grid gap-3 xl:grid-cols-3"><LabPanel title="Ingresos" action={<span className="rounded border border-white/[0.07] px-2 py-1 text-[7px] text-zinc-500">Este mes⌄</span>}><div className="mb-2 flex items-baseline gap-2"><span className="text-[18px] font-semibold">{money(facturadoMes)}</span><span className="text-[8px] text-[#55c765]">+22% vs mes anterior</span></div><div className="h-36"><LabLineChart points={ingresosAcumulado} labels={dayLabels} color="#ef202d" formatY={(v)=>`${Math.round(v/1000)}k €`}/></div></LabPanel>
        <LabPanel title="Cobros" action={<span className="rounded border border-white/[0.07] px-2 py-1 text-[7px] text-zinc-500">Este mes⌄</span>}><div className="mb-2 flex items-baseline gap-2"><span className="text-[18px] font-semibold">{money(cobradas)}</span><span className="text-[8px] text-[#55c765]">+20% vs mes anterior</span></div><div className="h-36"><LabBarChart labels={dayLabels} series={[{label:'Cobrados',color:'#55c765',values:cobradosPorDia},{label:'Pendientes',color:'#ef202d',values:pendientesPorDia}]} formatY={(v)=>`${Math.round(v/1000)}k €`}/></div></LabPanel>
        <LabPanel title="Estado de cobros"><div className="flex items-center gap-4"><LabDonut size={135} thickness={18} centerValue={money(pendienteTotal)} centerLabel="Pendiente" segments={[{label:'Cobradas',value:cobradas,color:'#55c765'},{label:'Pendientes',value:pendientesSinVencer,color:'#f59e0b'},{label:'Vencidas',value:vencidas,color:'#ef202d'}]}/><div className="min-w-0 flex-1 space-y-2 text-[8px]"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#55c765]"/><span className="text-zinc-500">Cobradas</span><span className="ml-auto text-zinc-300">{money(cobradas)}</span></div><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#f59e0b]"/><span className="text-zinc-500">Pendientes</span><span className="ml-auto text-zinc-300">{Math.round((pendientesSinVencer/totalCobros)*100)}%</span></div><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-[#ef202d]"/><span className="text-zinc-500">Vencidas</span><span className="ml-auto text-zinc-300">{money(vencidas)}</span></div></div></div></LabPanel>
      </div>
    </div>
    <FormModal open={open} onClose={()=>setOpen(false)} title="Nuevo documento"><form onSubmit={save} className="grid gap-3 md:grid-cols-2"><select value={form.tipo_documento} onChange={(e)=>setForm({...form,tipo_documento:e.target.value})}><option value="factura">Factura</option><option value="presupuesto">Presupuesto</option><option value="albaran">Albarán</option><option value="ticket">Ticket</option></select><select value={form.cliente_id} onChange={(e)=>setForm({...form,cliente_id:e.target.value})}><option value="">Sin cliente</option>{clientes.map((c)=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select><select value={form.estado} onChange={(e)=>setForm({...form,estado:e.target.value})}><option value="pendiente">Pendiente</option><option value="pagada">Pagada</option><option value="cancelada">Cancelada</option></select><input type="number" placeholder="IVA %" value={form.iva_porcentaje} onChange={(e)=>setForm({...form,iva_porcentaje:Number(e.target.value)})}/><input className="md:col-span-2" placeholder="Concepto" value={form.concepto} onChange={(e)=>setForm({...form,concepto:e.target.value})}/><input type="number" placeholder="Precio" value={form.precio} onChange={(e)=>setForm({...form,precio:Number(e.target.value)})}/><textarea className="md:col-span-2" placeholder="Notas" value={form.notas} onChange={(e)=>setForm({...form,notas:e.target.value})}/><button className="rounded-md bg-[#b92028] py-2.5 text-[10px] font-semibold text-white md:col-span-2">Crear documento</button></form></FormModal>
    <ConfirmModal open={Boolean(pendingDelete)} title={`Eliminar ${pendingDelete?.numero_documento||'este documento'}`} description="Esta acción eliminará también sus líneas de detalle. No se puede deshacer." confirmLabel="Sí, eliminar" danger loading={deleting} onConfirm={confirmDelete} onCancel={()=>setPendingDelete(null)}/>
  </LabShell>
}
