'use client'

import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'
import { getConfiguracionEmpresa, saveConfiguracionEmpresa, type ConfiguracionEmpresa } from '@/lib/services/configuracion'

type FormState=Partial<ConfiguracionEmpresa>
type Props={initial?:ConfiguracionEmpresa|null;onSaved?:()=>void}
const inputClass='w-full rounded-md border border-white/[0.08] bg-[#0d0f13] px-3 py-2.5 text-[10px] text-zinc-200 outline-none transition placeholder:text-zinc-700 focus:border-[#ef202d]/60'
const labelClass='mb-1.5 block text-[8px] font-medium uppercase tracking-[.08em] text-zinc-600'

export default function ConfigEmpresaForm({initial,onSaved}:Props){
  const [loading,setLoading]=useState(!initial);const [saving,setSaving]=useState(false);const [form,setForm]=useState<FormState>(initial||{})
  useEffect(()=>{if(initial){setForm(initial);setLoading(false);return}getConfiguracionEmpresa().then((data)=>{if(data)setForm(data)}).catch((error)=>toast.error(error.message||'Error cargando configuración')).finally(()=>setLoading(false))},[initial])
  function update<K extends keyof FormState>(key:K,value:FormState[K]){setForm((prev)=>({...prev,[key]:value}))}
  async function onSubmit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();try{setSaving(true);const saved=await saveConfiguracionEmpresa(form);setForm(saved);toast.success('Configuración guardada');onSaved?.()}catch(error:any){toast.error(error.message||'No se pudo guardar')}finally{setSaving(false)}}
  if(loading)return <div className="rounded-lg border border-white/[0.08] bg-[#0d0f13] p-6 text-[10px] text-zinc-500">Cargando configuración...</div>
  return <form onSubmit={onSubmit} className="space-y-4">
    <section className="rounded-lg border border-white/[0.07] bg-white/[0.012] p-4"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-[13px] font-semibold text-white">Datos de empresa</h2><p className="mt-1 text-[8px] text-zinc-600">Datos usados en facturas, presupuestos, albaranes y garantías.</p></div><button type="submit" disabled={saving} className="rounded-md bg-[#b92028] px-4 py-2 text-[9px] font-semibold text-white disabled:opacity-50">{saving?'Guardando...':'Guardar cambios'}</button></div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3"><Field label="Nombre comercial"><input className={inputClass} value={form.nombre_comercial||''} onChange={(e)=>update('nombre_comercial',e.target.value)}/></Field><Field label="Razón social"><input className={inputClass} value={form.razon_social||''} onChange={(e)=>update('razon_social',e.target.value)}/></Field><Field label="CIF / NIF"><input className={inputClass} value={form.cif||''} onChange={(e)=>update('cif',e.target.value)}/></Field><Field label="Dirección" span><input className={inputClass} value={form.direccion||''} onChange={(e)=>update('direccion',e.target.value)}/></Field><Field label="Código postal"><input className={inputClass} value={form.codigo_postal||''} onChange={(e)=>update('codigo_postal',e.target.value)}/></Field><Field label="Población"><input className={inputClass} value={form.poblacion||''} onChange={(e)=>update('poblacion',e.target.value)}/></Field><Field label="Provincia"><input className={inputClass} value={form.provincia||''} onChange={(e)=>update('provincia',e.target.value)}/></Field><Field label="Teléfono"><input className={inputClass} value={form.telefono||''} onChange={(e)=>update('telefono',e.target.value)}/></Field><Field label="Email"><input className={inputClass} value={form.email||''} onChange={(e)=>update('email',e.target.value)}/></Field><Field label="Web"><input className={inputClass} value={form.web||''} onChange={(e)=>update('web',e.target.value)}/></Field><Field label="Logo URL" span><input className={inputClass} value={form.logo_url||''} onChange={(e)=>update('logo_url',e.target.value)} placeholder="https://..."/></Field></div></section>
    <section className="rounded-lg border border-white/[0.07] bg-white/[0.012] p-4"><h2 className="mb-3 text-[12px] font-semibold text-white">Documentos y numeración</h2><div className="grid gap-3 md:grid-cols-3 lg:grid-cols-6"><Field label="IVA defecto"><input type="number" step="0.01" className={inputClass} value={form.iva_defecto??21} onChange={(e)=>update('iva_defecto',Number(e.target.value))}/></Field><Field label="Prefijo OT"><input className={inputClass} value={form.prefijo_ot||''} onChange={(e)=>update('prefijo_ot',e.target.value)}/></Field><Field label="Factura"><input className={inputClass} value={form.prefijo_factura||''} onChange={(e)=>update('prefijo_factura',e.target.value)}/></Field><Field label="Presupuesto"><input className={inputClass} value={form.prefijo_presupuesto||''} onChange={(e)=>update('prefijo_presupuesto',e.target.value)}/></Field><Field label="Albarán"><input className={inputClass} value={form.prefijo_albaran||''} onChange={(e)=>update('prefijo_albaran',e.target.value)}/></Field><Field label="Ticket"><input className={inputClass} value={form.prefijo_ticket||''} onChange={(e)=>update('prefijo_ticket',e.target.value)}/></Field></div></section>
    <section className="rounded-lg border border-white/[0.07] bg-white/[0.012] p-4"><h2 className="mb-3 text-[12px] font-semibold text-white">Textos legales</h2><div className="grid gap-3 lg:grid-cols-2"><Field label="Pie de factura"><textarea rows={5} className={inputClass} value={form.texto_pie_factura||''} onChange={(e)=>update('texto_pie_factura',e.target.value)}/></Field><Field label="Texto de garantía"><textarea rows={5} className={inputClass} value={form.texto_garantia||''} onChange={(e)=>update('texto_garantia',e.target.value)}/></Field></div></section>
  </form>
}
function Field({label,children,span=false}:{label:string;children:React.ReactNode;span?:boolean}){return <label className={span?'md:col-span-2':''}><span className={labelClass}>{label}</span>{children}</label>}
