'use client'

import { Suspense, useEffect, useState } from 'react'
import { useSearchParams, useRouter } from 'next/navigation'
import Link from 'next/link'
import { AlertTriangle, CheckCircle2, Clock3, FileQuestion, LogOut, RefreshCw } from 'lucide-react'
import { supabase } from '@/lib/supabase'
import { getMiSolicitud } from '@/lib/services/distribuidores'

function Content(){
  const params=useSearchParams(); const router=useRouter(); const estadoParam=params.get('estado')||'pendiente'; const [estado,setEstado]=useState(estadoParam); const [motivo,setMotivo]=useState<string|null>(null); const [loading,setLoading]=useState(false)
  async function refresh(){setLoading(true);try{const solicitud=await getMiSolicitud(); if(solicitud){setEstado(solicitud.estado);setMotivo(solicitud.motivo_estado);if(solicitud.estado==='aprobada')router.replace('/dashboard')}}finally{setLoading(false)}}
  useEffect(()=>{refresh()},[])
  const cfg:any={pendiente:{icon:Clock3,title:'Solicitud en revisión',text:'Nuestro equipo revisará tus datos desde Autokeys Core. Te avisaremos cuando tu cuenta esté activa.',tone:'text-amber-300 bg-amber-400/10 border-amber-400/25'},rechazada:{icon:AlertTriangle,title:'Solicitud no aprobada',text:'La solicitud ha sido rechazada. Contacta con Autokeys si necesitas más información.',tone:'text-red-300 bg-red-500/10 border-red-400/25'},informacion_solicitada:{icon:FileQuestion,title:'Necesitamos más información',text:'Autokeys ha solicitado información adicional antes de aprobar la cuenta.',tone:'text-sky-300 bg-sky-400/10 border-sky-400/25'},informacion:{icon:FileQuestion,title:'Necesitamos más información',text:'Autokeys ha solicitado información adicional antes de aprobar la cuenta.',tone:'text-sky-300 bg-sky-400/10 border-sky-400/25'}}[estado]||{icon:CheckCircle2,title:'Solicitud enviada',text:'La solicitud se ha registrado correctamente.',tone:'text-emerald-300 bg-emerald-400/10 border-emerald-400/25'}; const Icon=cfg.icon
  return <main className="grid min-h-screen place-items-center bg-[#030303] p-5 text-white"><div className="fixed inset-0 bg-[radial-gradient(circle_at_center,rgba(217,4,41,.18),transparent_35%)]"/><div className="relative w-full max-w-2xl rounded-[2rem] border border-white/12 bg-[#090b0f]/95 p-8 text-center shadow-[0_50px_150px_rgba(0,0,0,.75)] backdrop-blur-2xl md:p-12"><img src="/images/login/autokeys-logo-small.webp" className="mx-auto w-52" alt="Autokeys"/><div className={`mx-auto mt-9 grid h-20 w-20 place-items-center rounded-3xl border ${cfg.tone}`}><Icon size={38}/></div><p className="mt-7 text-xs font-black uppercase tracking-[.25em] text-red-400">AK Cloud Access</p><h1 className="mt-3 text-4xl font-black uppercase md:text-5xl">{cfg.title}</h1><p className="mx-auto mt-5 max-w-xl text-lg leading-8 text-white/50">{cfg.text}</p>{motivo&&<div className="mt-6 rounded-2xl border border-white/10 bg-white/[.04] p-4 text-left"><p className="text-xs font-black uppercase tracking-wider text-white/35">Mensaje de Autokeys</p><p className="mt-2 text-white/75">{motivo}</p></div>}<div className="mt-8 flex flex-wrap justify-center gap-3"><button onClick={refresh} disabled={loading} className="inline-flex items-center gap-2 rounded-2xl bg-red-600 px-5 py-3 text-sm font-black uppercase disabled:opacity-50"><RefreshCw size={17} className={loading?'animate-spin':''}/> Comprobar estado</button><button onClick={async()=>{await supabase.auth.signOut();router.push('/login')}} className="inline-flex items-center gap-2 rounded-2xl border border-white/12 bg-white/[.035] px-5 py-3 text-sm font-black uppercase text-white/65"><LogOut size={17}/> Cerrar sesión</button></div><Link href="/" className="mt-7 inline-block text-sm font-bold text-white/35 hover:text-white">Volver a la web pública</Link></div></main>
}
export default function Page(){return <Suspense fallback={null}><Content/></Suspense>}
