'use client'

import { Suspense, useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation'
import { supabase } from '@/lib/supabase'
import toast from 'react-hot-toast'
import { Mail, Lock, Eye, EyeOff, ShieldCheck, Layers, MonitorCheck, Headset, Phone, MessageCircle, Users, Car, FolderOpen, Receipt, UploadCloud, UserRound, UserPlus } from 'lucide-react'
import { LabLogoMark } from '@/components/lab'

function getStandaloneMode(){if(typeof window==='undefined')return false;const n=(window.navigator as Navigator&{standalone?:boolean}).standalone;return Boolean(n||window.matchMedia?.('(display-mode: standalone)').matches)}
const FEATURES=[{icon:ShieldCheck,title:'Acceso seguro',desc:'Protegemos tus datos con los más altos estándares de seguridad.'},{icon:Layers,title:'Gestión centralizada',desc:'Toda la información de tu taller organizada y siempre disponible.'},{icon:MonitorCheck,title:'Seguimiento del taller',desc:'Controla trabajos, expedientes y estado de cada proyecto en tiempo real.'},{icon:Headset,title:'Soporte técnico',desc:'Asistencia especializada para que tu taller nunca se detenga.'}]

function LoginContent(){
  const router=useRouter();const searchParams=useSearchParams()
  const fallbackNext=useMemo(()=>typeof window==='undefined'?'/':getStandaloneMode()?'/mobile':'/',[])
  const next=searchParams.get('next')||fallbackNext
  const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [showPassword,setShowPassword]=useState(false);const [remember,setRemember]=useState(true);const [loading,setLoading]=useState(false);const [resetMode,setResetMode]=useState(false);const [resetEmail,setResetEmail]=useState('');const [resetLoading,setResetLoading]=useState(false)
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data.session)router.replace(next)})},[router,next])

  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();try{setLoading(true);const cleanEmail=email.trim().toLowerCase();const {data,error}=await supabase.auth.signInWithPassword({email:cleanEmail,password});if(error)throw error;const authUserId=data.user?.id;const {data:perfil,error:perfilError}=await supabase.from('usuarios_app').select('*').or(`auth_user_id.eq.${authUserId},email.eq.${cleanEmail}`).maybeSingle();if(perfilError)throw perfilError;if(perfil){if(perfil.activo===false){await supabase.auth.signOut();toast.error('Usuario bloqueado. Contacta con administración');return}if(!perfil.auth_user_id&&authUserId)await supabase.from('usuarios_app').update({auth_user_id:authUserId}).eq('id',perfil.id);await supabase.from('usuarios_app').update({ultimo_acceso:new Date().toISOString()}).eq('id',perfil.id);toast.success(`Bienvenido, ${perfil.nombre||cleanEmail}`);router.replace(next);router.refresh();return}const {data:distribuidor,error:distError}=await supabase.from('akcloud_distribuidores').select('id, empresa, estado').eq('auth_user_id',authUserId).maybeSingle();if(distError)throw distError;if(distribuidor){if(distribuidor.estado!=='activo'){await supabase.auth.signOut();toast.error(`Tu cuenta está ${distribuidor.estado}. Contacta con Autokeys Lab.`);return}toast.success(`Bienvenido, ${distribuidor.empresa}`);router.replace(next.startsWith('/mi-cuenta')?next:'/mi-cuenta');router.refresh();return}await supabase.auth.signOut();toast.error('Tu cuenta no tiene un perfil vinculado en Autokeys Lab')}catch(error:any){toast.error(error.message||'No se pudo iniciar sesión')}finally{setLoading(false)}}
  async function oauth(provider:'google'|'azure'){try{const {error}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo:`${window.location.origin}${next}`}});if(error)throw error}catch(error:any){toast.error(error.message||'Este proveedor no está configurado todavía')}}
  async function submitReset(e:React.FormEvent){e.preventDefault();setResetLoading(true);try{const {error}=await supabase.auth.resetPasswordForEmail(resetEmail.trim().toLowerCase(),{redirectTo:`${window.location.origin}/restablecer-password`});if(error)throw error;toast.success('Te hemos enviado un email para restablecer tu contraseña');setResetMode(false)}catch(error:any){toast.error(error.message||'No se pudo enviar el email de recuperación')}finally{setResetLoading(false)}}

  return <main className="relative min-h-screen overflow-hidden bg-[#06080b] text-white">
    <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_18%_25%,rgba(239,32,45,.12),transparent_28%),radial-gradient(circle_at_92%_48%,rgba(239,32,45,.08),transparent_22%),linear-gradient(135deg,#06080b,#0a0d11_52%,#06080b)]"/>
    <div className="pointer-events-none fixed inset-0 opacity-[.08] [background-image:linear-gradient(rgba(255,255,255,.06)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.06)_1px,transparent_1px)] [background-size:90px_90px]"/>
    <div className="relative mx-auto grid min-h-screen max-w-[1760px] lg:grid-cols-[1fr_1.02fr]">
      <section className="relative flex min-h-[720px] flex-col justify-between overflow-hidden border-b border-white/[0.07] px-8 py-8 lg:border-b-0 lg:border-r lg:px-12 lg:py-10 xl:px-16">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_58%_48%,rgba(255,255,255,.055),transparent_34%),linear-gradient(180deg,rgba(255,255,255,.012),transparent)]"/>
        <div className="pointer-events-none absolute bottom-[22%] right-[-5%] h-[180px] w-[430px] rounded-[50%] border border-white/[0.035] bg-black/40 shadow-[0_0_80px_rgba(239,32,45,.06)] before:absolute before:bottom-[24px] before:left-[65px] before:h-[52px] before:w-[300px] before:rounded-[50%] before:border before:border-white/[0.04] before:bg-[#0c1015] after:absolute after:bottom-[18px] after:right-[52px] after:h-[34px] after:w-[90px] after:rounded-full after:bg-[#ef202d]/20"/>

        <div className="relative z-10">
          <div className="flex items-center gap-4"><LabLogoMark size={64}/><div><div className="text-[32px] font-bold leading-none tracking-[-.025em]">Autokeys Lab</div><div className="mt-2 text-[15px] text-zinc-300">by Autokeys Remaps Pro</div></div></div>
          <h1 className="mt-10 max-w-xl text-[34px] font-semibold leading-tight tracking-[-.03em] sm:text-[40px]">Acceso al <span className="text-[#ef202d]">ERP</span> profesional</h1>
          <p className="mt-3 max-w-[520px] text-[14px] leading-6 text-zinc-400">Gestiona tu taller de forma eficiente: clientes, vehículos, expedientes, facturación y file service en un solo lugar.</p>
          <div className="mt-7 space-y-3.5">{FEATURES.map((f)=>{const Icon=f.icon;return <div key={f.title} className="flex max-w-[500px] items-start gap-3"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-xl border border-[#ef202d]/25 bg-[#ef202d]/[0.07] text-[#ef202d]"><Icon size={21}/></div><div><div className="text-[13px] font-semibold text-zinc-100">{f.title}</div><div className="mt-1 max-w-[340px] text-[11px] leading-4 text-zinc-500">{f.desc}</div></div></div>})}</div>
        </div>

        <div className="relative z-10 mt-10 rounded-2xl border border-[#ef202d]/20 bg-[#090c10]/80 p-5 shadow-[0_25px_80px_rgba(0,0,0,.3)] backdrop-blur-xl">
          <div className="relative grid grid-cols-3 items-center gap-y-4">
            <Module icon={Users} label="Clientes"/><div/><Module icon={FolderOpen} label="Expedientes"/>
            <Module icon={Car} label="Vehículos"/><div className="mx-auto grid h-20 w-24 place-items-center rounded-xl border border-[#ef202d]/35 bg-[radial-gradient(circle_at_center,rgba(239,32,45,.25),rgba(8,10,13,.95)_64%)] shadow-[0_0_35px_rgba(239,32,45,.24)]"><span className="text-[24px] font-black italic tracking-[-.12em] text-[#ef202d]">AK</span></div><Module icon={Receipt} label="Facturación"/>
            <div/><Module icon={UploadCloud} label="File Service"/><div/>
          </div>
        </div>
        <div className="relative z-10 mt-5 text-center text-[10px] text-zinc-600">© 2026 <span className="text-[#ef202d]">Autokeys Lab</span> by Autokeys Remaps Pro. Todos los derechos reservados.</div>
      </section>

      <section className="relative flex items-center justify-center px-5 py-8 sm:px-8 lg:px-10 xl:px-16">
        <div className="w-full max-w-[680px] rounded-[22px] border border-white/[0.16] bg-[#0a0d11]/88 p-5 shadow-[0_45px_120px_rgba(0,0,0,.55)] backdrop-blur-2xl sm:p-7 lg:p-8">
          <div className="grid grid-cols-2 border-b border-white/[0.09]"><button className="flex items-center justify-center gap-2 border-b-2 border-[#ef202d] bg-white/[0.018] px-4 py-4 text-[13px] font-semibold text-[#ef202d]"><UserRound size={17}/>Iniciar sesión</button><Link href="/register" className="flex items-center justify-center gap-2 px-4 py-4 text-[13px] font-medium text-zinc-500 hover:text-zinc-300"><UserPlus size={17}/>Solicitar acceso</Link></div>
          {!resetMode ? <>
            <div className="pt-7"><h2 className="text-[26px] font-semibold tracking-[-.025em]">Bienvenido de nuevo</h2><p className="mt-1.5 text-[13px] text-zinc-500">Inicia sesión para acceder a tu plataforma ERP.</p></div>
            <form onSubmit={submit} className="mt-7 space-y-4"><FieldLabel label="Correo electrónico"><Mail size={16} className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-500"/><input required type="email" value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="tu@email.com" className="h-12 w-full rounded-lg border border-white/[0.12] bg-[#0b0e12] pl-12 pr-4 text-[12px] outline-none focus:border-[#ef202d]/55"/></FieldLabel><FieldLabel label="Contraseña"><Lock size={16} className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-500"/><input required type={showPassword?'text':'password'} value={password} onChange={(e)=>setPassword(e.target.value)} placeholder="••••••••••••" className="h-12 w-full rounded-lg border border-white/[0.12] bg-[#0b0e12] pl-12 pr-12 text-[12px] outline-none focus:border-[#ef202d]/55"/><button type="button" onClick={()=>setShowPassword((v)=>!v)} className="absolute right-4 top-1/2 -translate-y-1/2 text-zinc-600">{showPassword?<EyeOff size={16}/>:<Eye size={16}/>}</button></FieldLabel>
              <div className="flex items-center justify-between text-[11px]"><label className="flex items-center gap-2 text-zinc-400"><input type="checkbox" checked={remember} onChange={(e)=>setRemember(e.target.checked)} className="accent-[#ef202d]"/>Recordar sesión</label><button type="button" onClick={()=>{setResetMode(true);setResetEmail(email)}} className="font-medium text-[#ef202d]">¿Olvidaste tu contraseña?</button></div>
              <button disabled={loading} className="flex h-[52px] w-full items-center justify-center rounded-lg bg-gradient-to-r from-[#ef202d] to-[#e61d29] text-[14px] font-semibold shadow-[0_12px_35px_rgba(239,32,45,.22)] disabled:opacity-50">{loading?'Iniciando sesión...':'Iniciar sesión   →'}</button>
            </form>
            <div className="my-5 flex items-center gap-3 text-[10px] text-zinc-600"><div className="h-px flex-1 bg-white/[0.09]"/>o continúa con<div className="h-px flex-1 bg-white/[0.09]"/></div>
            <div className="grid grid-cols-2 gap-3"><button onClick={()=>oauth('google')} className="flex h-12 items-center justify-center gap-2 rounded-lg border border-white/[0.11] bg-white/[0.018] text-[11px] font-medium text-zinc-300">G&nbsp; Continuar con Google</button><button onClick={()=>oauth('azure')} className="flex h-12 items-center justify-center gap-2 rounded-lg border border-white/[0.11] bg-white/[0.018] text-[11px] font-medium text-zinc-300"><span className="grid grid-cols-2 gap-[1px]"><i className="h-2 w-2 bg-[#f35325]"/><i className="h-2 w-2 bg-[#81bc06]"/><i className="h-2 w-2 bg-[#05a6f0]"/><i className="h-2 w-2 bg-[#ffba08]"/></span>Continuar con Microsoft</button></div>
            <div className="mt-5 grid grid-cols-3 gap-2"><Contact icon={Mail} title="Email" value="info@autokeyspro.es"/><Contact icon={Phone} title="Teléfono" value="+34 953 85 27 78"/><Contact icon={MessageCircle} title="WhatsApp" value="+34 632 98 26 46" green/></div>
            <div className="mt-4 flex items-center gap-3 rounded-lg border border-white/[0.11] bg-[#090c10] px-4 py-3 text-[9px] text-zinc-500"><ShieldCheck size={16} className="text-[#ef202d]"/>Conexión segura y cifrada. Utilizamos SSL y cumplimos con las normativas de privacidad.</div>
          </> : <div className="py-7"><h2 className="text-[24px] font-semibold">Recuperar contraseña</h2><p className="mt-1 text-[12px] text-zinc-500">Te enviaremos un enlace para restablecerla.</p><form onSubmit={submitReset} className="mt-6 space-y-4"><FieldLabel label="Correo electrónico"><Mail size={16} className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-500"/><input required type="email" value={resetEmail} onChange={(e)=>setResetEmail(e.target.value)} className="h-12 w-full rounded-lg border border-white/[0.12] bg-[#0b0e12] pl-12 pr-4 text-[12px] outline-none"/></FieldLabel><button disabled={resetLoading} className="h-12 w-full rounded-lg bg-[#b92028] text-[12px] font-semibold disabled:opacity-50">{resetLoading?'Enviando...':'Enviar enlace de recuperación'}</button><button type="button" onClick={()=>setResetMode(false)} className="w-full text-center text-[10px] text-zinc-500">Volver a iniciar sesión</button></form></div>}
        </div>
      </section>
    </div>
  </main>
}

function Module({icon:Icon,label}:{icon:any;label:string}){return <div className="flex flex-col items-center gap-1.5"><div className="grid h-12 w-12 place-items-center rounded-xl border border-white/[0.12] bg-[#0c0f13] text-zinc-300"><Icon size={19}/></div><span className="text-[9px] text-zinc-400">{label}</span></div>}
function FieldLabel({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-[11px] text-zinc-300">{label}</span><div className="relative">{children}</div></label>}
function Contact({icon:Icon,title,value,green=false}:{icon:any;title:string;value:string;green?:boolean}){return <div className="flex items-center gap-2 rounded-lg border border-white/[0.1] bg-[#090c10] px-3 py-3"><Icon size={16} className={green?'text-[#27c468]':'text-[#ef202d]'}/><div className="min-w-0"><div className="text-[9px] font-medium text-zinc-300">{title}</div><div className="truncate text-[8px] text-zinc-600">{value}</div></div></div>}
export default function LoginPage(){return <Suspense fallback={<main className="grid min-h-screen place-items-center bg-[#07080b] text-zinc-500">Cargando acceso...</main>}><LoginContent/></Suspense>}
